version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "monthly"
      assignees:
          - "jsafarik"
      commit-message:
          prefix: "[Dependabot]"
