name: 'prepare-env'
description: 'Prepare scine CI/CD environment'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        path: 'master'
    - uses: actions/checkout@v3
      with:
        path: 'db'
        ref: 'refs/heads/db'
    - name: 'Generate site'
      run: cp $GITHUB_WORKSPACE/db/videos.json $GITHUB_WORKSPACE/master/src/lib/videos.json
      shell: bash
