# https://github.com/firebase/firebase-tools

name: deploy-live
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add CI/CD
        uses: actions/checkout@v4
        with:
          path: 'cicd'
      - uses: ./cicd/.github/actions/generate-site
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: scine-web
          channelId: live
          entrypoint: master
