name: preview-pr
'on':
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '.github/**'
      - 'README.md'

permissions:
  pull-requests: write
  checks: write

jobs:
  build_and_preview:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Add CI/CD
        uses: actions/checkout@v4
        with:
          path: 'cicd'
      - uses: ./cicd/.github/actions/prepare-env
      - uses: ./cicd/.github/actions/generate-site
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: scine-web
          channelId: ${{ inputs.channel }}
          entrypoint: master
