name: register-channel
'on':
  workflow_dispatch:
    inputs:
      channelHandle:
        description: 'Handle of youtube channel - without "@"'
        type: string
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update_channels:
    runs-on: ubuntu-latest
    env:
      CHANNEL: ${{ inputs.channelHandle }}
      API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Generate channel entry
        run: npm ci && npm run register-channel -- $CHANNEL -y
