name: update-videos
'on':
  schedule:
    - cron: '0 0 * * *' # Run at 00:00
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_videos:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
      FIRESTORE_USERNAME: ${{ secrets.FIRESTORE_USERNAME }}
      FIRESTORE_PASSWORD: ${{ secrets.FIRESTORE_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Update videos in database
        run: npm ci && npm run update-videos
