name: update-channels
'on':
  workflow_dispatch:
    inputs:
      channelName:
        description: 'Name of youtube channel - without "@"'
        type: string
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update_channels:
    runs-on: ubuntu-latest
    env:
      CHANNEL: ${{ inputs.channelName }}
      NEW_CHANNEL_FILE: db/new-channel.json
      CHANNELS_FILE: db/channels.json
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Add CI/CD
        uses: actions/checkout@v4
        with:
          path: 'cicd'
      - uses: ./cicd/.github/actions/prepare-env
      - name: Generate channel entry
        run: |
          pushd master
          npm ci
          npm run --silent get-channel -- $CHANNEL -r > $GITHUB_WORKSPACE/$NEW_CHANNEL_FILE
          echo 'Generated channel:'
          cat $GITHUB_WORKSPACE/$NEW_CHANNEL_FILE
          popd
      - name: Add channel entry
        run: |
            echo "Adding new entry for $CHANNEL"
            cat $GITHUB_WORKSPACE/$CHANNELS_FILE | \
              jq --arg NEW_CHANNEL $CHANNEL '[.[] | select(.name!=$NEW_CHANNEL)]' | \
              jq --arg NEW_CHANNEL "$(cat $GITHUB_WORKSPACE/$NEW_CHANNEL_FILE)" '. += [ $NEW_CHANNEL | fromjson ]' | \
              jq '. | sort_by(.name)' \
              > $GITHUB_WORKSPACE/$CHANNELS_FILE
      - name: Commit db
        run: |
          pushd db
          if ! git diff --exit-code channels.json; then
            echo "content updated, pushing new content"
            git config --global user.name 'Jan Safarik'
            git config --global user.email 'jsafarik@users.noreply.github.com'
            git commit -am "[channels] Automatically update channels.json from GH workflow"
            git push origin db:db-$CHANNEL
            GITHUB_WORKFLOW_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
            gh pr create \
              -B db \
              -H db-$CHANNEL \
              --title "Add $CHANNEL channel to db" \
              --body "Created by Github action $GITHUB_WORKFLOW_URL"
          else
            echo "No change detected, skipping push"
          fi
          popd
